// les lettre en minuscule sont le ' r=R'

// todo faire les cas de test
export const algof2L: string[] = [
  "URU'R'",
  'yURUR',
  'yRUR',
  'RUR',
  'uRurUyruR',
  'uRUrURUr',
  '	uRUUrUyruR',
  '	uRUrURUr',
  'uRUUrUyruR',
  'rUURRURRUr',
  'yUrURuruR',
  'uRURURUR',
  'uRUrUURur',
  'yUruRUUrUR',
  'uRUUrUURur',
  'yUrUURUUrUR',
  'URUUrURur',
  '	yurUURurUR',
  '	UURUrURur',
  'yUUruRurUR',
  '	yrURUUyRUr',
  'RurUUyruR',
  '	RUUruRUr',
  '	yrUURUruR',
  '	URuruRurURur',
  'FURurfRur',
  '	ufRUrurFr',
  '	URurufUF',
  '	RurURur',
  '	yrURurUR',
  '	yruRUruR',
  '	RUruRUr',
  'RurUyrUR',
  'URurURurURur',
  '	uRurUURur',
  '	URUrUURUr',
  'uRUrUyruR',
  '	UfuFuRUr',
  '	RurDwrUURUUrUR',
  '	RuruRUrUURur',
  '	RurURUUrURur',
  '	fUFUURUrURur',
  '	RUruRurUUyruR',
];

export const algoOLL: string[] = [
  "RU2R2FRF'U2R'FRF'",
  "FRUR'U'F'fRUR'U'f'",
  "l L2 U' L U' l' U2 lU' L l'",
  "r' R2 U R' U r U2 r' U R' r",
  "r' U2 R U R' U r2U2 R' U' R U' r'",
  "r U R' U R U2 r2U' R U' R' U2 r",
  "R U R' U R' F RF' U2 R' F R F'",
  "r' R U R U R' U'r2 R2 U R U' r'",
  "R U2 R2 U' R U'R' U2 F R F'",
  "F R U R' U' R F' rU R' U' r'",
  "f R U R' U' R U R'U' f",
  "R' U' R U' R' U F'U F R",
  "rUUR'U'RUR'U'RU'r'",
  "l'UULUL'U'LUL'Ul",
  "FR'F2LF2RF2L'F",
  'Constante4',
  "FRUR'U'RUR'U'F'",
  "F'L'U'LUL'U'LUF",
  "rUR'URUUr'",
  "l'U'LU'L'UUl",
  "rRRU'RU'R'UURU'Rr'",
  "l'L2UL'ULUUL'UL'l",
  "R'U'RFR'F'UFRF'",
  "LUL'F'LFU'F'L'F",
  "l'UULUL'Ul",
  "rUUR'U'RU'r'",
  "FURUUR'U'RUR'F'",
  "F'U'L'UULUL'U'LF",
  "r'U'rR'U'RUr'Ur",
  "Ul'LUL'U'lU'l'",
  "RUR'URUUR'FRUR'U'F'",
  "L'U'LU'L'UULF'L'U'LUF",
  "RUR'U'RU'R'F'U'FRUR'",
  "L'U'LUL'ULFUF'L'U'L",
  "R'U'FURU'R'F'R",
  "LUF'U'L'ULFL'",
  "FR'F'RURU'R'",
  "fRUR'U'f'",
  "f'L'U'LUf",
  "RUURRFRF'RUUR'",
  "FRUR'U'F'",
  "RUR'U'R'FRF'",
  "LF'L'U'LUFU'L'",
  "R'FRUR'U'F'UR",
  "FUF'U'R'F'LFr'R",
  "R'U'R'FRF'UR",
  "RUR'URU'R'U'R'FRF'",
  "L'U'LU'L'ULULF'L'F",
  "RUR'U'R'rURU'r'",
  "rUR'U'r'RURU'R'",
  "RUR'URUUR'",
  "L'U'LU'L'UUL",
  "FR'F'rURU'r'",
  "rUR'U'r'FRF'",
  "R'UURFU'R'U'RUF'",
  "RUURRU'RRU'RRUUR",
  "RUUR'U'RUR'U'RU'R'",
];
export const algoPLL: string[] = [
  'rrrrr',
  "RRU'R'U'RURURU'R",
  "R'UR'U'R'U'R'URURR",
  "UR'U'RU'RURU'R'URURRU'R'U",
  'rrrr',
  "RUR'FRUR'U'R'F'RRU'R'U'",
  "L'U'LF'L'U'LULFLLULU",
  "R'UURUUR'F'RUR'U'R'FRRU'",
  "LUUL'UULFL'U'LULF'LLU",
  "RUR'U'R'F'RRU'R'U'RUR'F",
  "R'URU'RRFU'F'URF'R'FRRU'",
  "L'URU'LUL'UR'U'LUURUUR'",
  'RRR',
  "R'UR'F'RFRU'R'FUF'RUR'U'R",
  "LU'LFL'F'L'ULF'U'FL'U'LUL'",
  "F'RU'R'U'RUR'FRUR'U'R'F'RF",
  'rrr',
  'rrrr',
];
export const mettre_algof2L: string[] = [
  "URU'R'",
  'yURUR',
  'yRUR',
  'RUR',
  'uRurUyruR',
  'uRUrURUr',
  '	uRUUrUyruR',
  '	uRUrURUr',
  'uRUUrUyruR',
  'rUURRURRUr',
  'yUrURuruR',
  'uRURURUR',
  'uRUrUURur',
  'yUruRUUrUR',
  'uRUUrUURur',
  'yUrUURUUrUR',
  'URUUrURur',
  '	yurUURurUR',
  '	UURUrURur',
  'yUUruRurUR',
  '	yrURUUyRUr',
  'RurUUyruR',
  '	RUUruRUr',
  '	yrUURUruR',
  '	URuruRurURur',
  'FURurfRur',
  '	ufRUrurFr',
  '	URurufUF',
  '	RurURur',
  '	yrURurUR',
  '	yruRUruR',
  '	RUruRUr',
  'RurUyrUR',
  'URurURurURur',
  '	uRurUURur',
  '	URUrUURUr',
  'uRUrUyruR',
  '	UfuFuRUr',
  '	RurDwrUURUUrUR',
  '	RuruRUrUURur',
  '	RurURUUrURur',
  '	fUFUURUrURur',
  '	RUruRurUUyruR',
];

export const mettre_algoOLL: string[] = [
  "F R' F' R U2' F R' F' R2' U2' R'",
  "f U R U' R' f' F U R U' R' F'",
  "F U R U' R' F' U f U R U' R' f'",
  "F U R U' R' F' U' f U R U' R' f' ",
  "r' U' R U' R' U2' r",
  "r U R' U R U2' r'",
  "r U2' R' U' R U' r'",
  "r' U2' R U R' U r",
  "F U R U' R2' F' R U R U' R' ",
  "R U2' R' F R' F' R U' R U' R'",
  "fRUR'U'RUR'U'f",
  "F U R U' R' F' U' F U R U' R' F'",
  "F' U' F r U' r' U r U r'",
  "F U F' R' F R U' R' F' R",
  "r' U' r U' R' U R r' U r",
  'Constante4',
  "FRUR'U'RUR'U'F'",
  "F'L'U'LUL'U'LUF",
  "rUR'URUUr'",
  "l'U'LU'L'UUl",
  "rRRU'RU'R'UURU'Rr'",
  "l'L2UL'ULUUL'UL'l",
  "R'U'RFR'F'UFRF'",
  "LUL'F'LFU'F'L'F",
  "l'UULUL'Ul",
  "rUUR'U'RU'r'",
  "FURUUR'U'RUR'F'",
  "F'U'L'UULUL'U'LF",
  "r'U'rR'U'RUr'Ur",
  "Ul'LUL'U'lU'l'",
  "RUR'URUUR'FRUR'U'F'",
  "L'U'LU'L'UULF'L'U'LUF",
  "RUR'U'RU'R'F'U'FRUR'",
  "L'U'LUL'ULFUF'L'U'L",
  "R'U'FURU'R'F'R",
  "LUF'U'L'ULFL'",
  "FR'F'RURU'R'",
  "fRUR'U'f'",
  "f'L'U'LUf",
  "RUURRFRF'RUUR'",
  "FRUR'U'F'",
  "RUR'U'R'FRF'",
  "LF'L'U'LUFU'L'",
  "R'FRUR'U'F'UR",
  "FUF'U'R'F'LFr'R",
  "R'U'R'FRF'UR",
  "RUR'URU'R'U'R'FRF'",
  "L'U'LU'L'ULULF'L'F",
  "RUR'U'R'rURU'r'",
  "rUR'U'r'RURU'R'",
  "RUR'URUUR'",
  "L'U'LU'L'UUL",
  "FR'F'rURU'r'",
  "rUR'U'r'FRF'",
  "R'UURFU'R'U'RUF'",
  "RUURRU'RRU'RRUUR",
  "RUUR'U'RUR'U'RU'R'",
];
export const mettre_algoPLL: string[] = [
  'rrrrr',
  "RRU'R'U'RURURU'R",
  "R'UR'U'R'U'R'URURR",
  "UR'U'RU'RURU'R'URURRU'R'U",
  'rrrr',
  "RUR'FRUR'U'R'F'RRU'R'U'",
  "L'U'LF'L'U'LULFLLULU",
  "R'UURUUR'F'RUR'U'R'FRRU'",
  "LUUL'UULFL'U'LULF'LLU",
  "RUR'U'R'F'RRU'R'U'RUR'F",
  "R'URU'RRFU'F'URF'R'FRRU'",
  "L'URU'LUL'UR'U'LUURUUR'",
  'RRR',
  "R'UR'F'RFRU'R'FUF'RUR'U'R",
  "LU'LFL'F'L'ULF'U'FL'U'LUL'",
  "F'RU'R'U'RUR'FRUR'U'R'F'RF",
  'rrr',
  'rrrr',
];
