// les lettre en minuscule sont le ' r=R'
export const algof2L: string[] = [
  'URur ',
  'yURURf',
  'yRUR',
  'RUR',
  'uRurUyruR',
  'uRUrURUr',
  '	uRUUrUyruR',
  '	uRUrURUr',
  'uRUUrUyruR',
  'rUURRURRUr',
  'yUrURuruR',
  'uRURURUR',
  'uRUrUURur',
  'yUruRUUrUR',
  'uRUUrUURur',
  'yUrUURUUrUR',
  'URUUrURur',
  '	yurUURurUR',
  '	UURUrURur',
  'yUUruRurUR',
  '	yrURUUyRUr',
  'RurUUyruR',
  '	RUUruRUr',
  '	yrUURUruR',
  '	URuruRurURur',
  'FURurfRur',
  '	ufRUrurFr',
  '	URurufUF',
  '	RurURur',
  '	yrURurUR',
  '	yruRUruR',
  '	RUruRUr',
  'RurUyrUR',
  'URurURurURur',
  '	uRurUURur',
  '	URUrUURUr',
  'uRUrUyruR',
  '	UfuFuRUr',
  '	RurDwrUURUUrUR',
  '	RuruRUrUURur',
  '	RurURUUrURur',
  '	fUFUURUrURur',
  '	RUruRurUUyruR',
];
export const algoPLL: string[] = [
  'Constante 1',
  'Constante 2',
  'Constante 3',
  'Constante 4',
];

export const algoOLL: string[] = [
  'Constante 1',
  'Constante 2',
  'Constante 3',
  'Constante 4',
];
