// les lettre en minuscule sont le ' r=R'

export const algof2L: string[] = [
  "URU'R'",
  'yURUR',
  'yRUR',
  'RUR',
  'uRurUyruR',
  'uRUrURUr',
  '	uRUUrUyruR',
  '	uRUrURUr',
  'uRUUrUyruR',
  'rUURRURRUr',
  'yUrURuruR',
  'uRURURUR',
  'uRUrUURur',
  'yUruRUUrUR',
  'uRUUrUURur',
  'yUrUURUUrUR',
  'URUUrURur',
  '	yurUURurUR',
  '	UURUrURur',
  'yUUruRurUR',
  '	yrURUUyRUr',
  'RurUUyruR',
  '	RUUruRUr',
  '	yrUURUruR',
  '	URuruRurURur',
  'FURurfRur',
  '	ufRUrurFr',
  '	URurufUF',
  '	RurURur',
  '	yrURurUR',
  '	yruRUruR',
  '	RUruRUr',
  'RurUyrUR',
  'URurURurURur',
  '	uRurUURur',
  '	URUrUURUr',
  'uRUrUyruR',
  '	UfuFuRUr',
  '	RurDwrUURUUrUR',
  '	RuruRUrUURur',
  '	RurURUUrURur',
  '	fUFUURUrURur',
  '	RUruRurUUyruR',
];

export const algoOLL: string[] = [
  "R2U2RFRF'2UR'FRF'",
  "FRUR'U'F'fRUR'U'f'",
  "lL2U'LU'l'UUlU'Ll'",
  "r'RRUR'UrUUr'UR'r",
  "r'UURUR'UrRUUR'U'RU'r'",
  "rUR'URUUrRU'RU'R'UUr",
  "RUR'UR'FRF'UUR'FRF'",
  "r'RURUR'U'rRRRURU'r'",
  "RUURRU'RU'R'UUFRF'",
  "FRUR'U'RF'rUR'U'r'",
  "fRUR'U'RUR'U'f",
  "R'U'RU'R'UF'UFR",
  "rUUR'U'RUR'U'RU'r'",
  "l'UULUL'U'LUL'Ul",
  "FR'F2LF2RF2L'F",
  'Constante4',
  "FRUR'U'RUR'U'F'",
  "F'L'U'LUL'U'LUF",
  "rUR'URUUr'",
  "l'U'LU'L'UUl",
  "rRRU'RU'R'UURU'Rr'",
  "l'L2UL'ULUUL'UL'l",
  "R'U'RFR'F'UFRF'",
  "LUL'F'LFU'F'L'F",
  "l'UULUL'Ul",
  "rUUR'U'RU'r'",
  "FURUUR'U'RUR'F'",
  "F'U'L'UULUL'U'LF",
  "r'U'rR'U'RUr'Ur",
  "Ul'LUL'U'lU'l'",
  "RUR'URUUR'FRUR'U'F'",
  "L'U'LU'L'UULF'L'U'LUF",
  "RUR'U'RU'R'F'U'FRUR'",
  "L'U'LUL'ULFUF'L'U'L",
  "R'U'FURU'R'F'R",
  "LUF'U'L'ULFL'",
  "FR'F'RURU'R'",
  "fRUR'U'f'",
  "f'L'U'LUf",
  "RUURRFRF'RUUR'",
  "FRUR'U'F'",
  "RUR'U'R'FRF'",
  "LF'L'U'LUFU'L'",
  "R'FRUR'U'F'UR",
  "FUF'U'R'F'LFr'R",
  "R'U'R'FRF'UR",
  "RUR'URU'R'U'R'FRF'",
  "L'U'LU'L'ULULF'L'F",
  "RUR'U'R'rURU'r'",
  "rUR'U'r'RURU'R'",
  "RUR'URUUR'",
  "L'U'LU'L'UUL",
  "FR'F'rURU'r'",
  "rUR'U'r'FRF'",
  "R'UURFU'R'U'RUF'",
  "RUURRU'RRU'RRUUR",
  "RUUR'U'RUR'U'RU'R'",
];
export const algoPLL: string[] = [
  'rrrrr',
  "RRU'R'U'RURURU'R",
  "R'UR'U'R'U'R'URURR",
  "UR'U'RU'RURU'R'URURRU'R'U",
  'rrrr',
  "RUR'FRUR'U'R'F'RRU'R'U'",
  "L'U'LF'L'U'LULFLLULU",
  "R'UURUUR'F'RUR'U'R'FRRU'",
  "LUUL'UULFL'U'LULF'LLU",
  "RUR'U'R'F'RRU'R'U'RUR'F",
  "R'URU'RRFU'F'URF'R'FRRU'",
  "L'URU'LUL'UR'U'LUURUUR'",
  'RRR',
  "R'UR'F'RFRU'R'FUF'RUR'U'R",
  "LU'LFL'F'L'ULF'U'FL'U'LUL'",
  "F'RU'R'U'RUR'FRUR'U'R'F'RF",
  'rrr',
  'rrrr',
];
